linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  funlen:
    lines: 100
    statements: 50

run:
  issues-exit-code: 1
  # Include test files or not.
  # Default: true
  tests: false
  # List of build tags, all linters use it.
  # Default: [].
  build-tags:
    - mytag
  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path.
  # Default value is empty list,
  # but default dirs are skipped independently of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  skip-dirs:
    - src/external_libs
    - autogenerated_by_my_lib
    - playground
    - fixtures
    - testdata
    - examples
    - demo
    - ".*/ref/"
    - ".*/save/"
    - ".*/bin/"
    - "ci/"
  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  skip-dirs-use-default: false
  # Which files to skip: they will be analyzed, but issues from them won't be reported.
  # Default value is empty list,
  # but there is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  skip-files:
    - ".*\\.my\\.go$"
    - lib/bad.go

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    #/- bodyclose
    #- deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    #- exhaustive
    - exportloopref
    - funlen
    - goconst
    #- gocritic
    - gofmt
    #- goimports
    #- gomnd
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    #/- gosimple
    - govet
    - ineffassign
    #/- interfacer
    #- maligned
    - misspell
    #- nolintlint
    #- nakedret
    - prealloc
    - predeclared
    - revive
    #/- staticcheck
    #- structcheck
    #/- stylecheck
    #- thelper
    #/- tparallel
    #- typecheck
    - unconvert
    #- unparam
    - varcheck
    - whitespace
    #- wsl
#linters:
#  enable:
#    - bodyclose
#    - dogsled
#    - errcheck
#    - errname
#    - errorlint
#    #    - exhaustive
#    #    - exportloopref
#    #    - funlen
#    #    - gochecknoinits
#    #    - goconst
#    #    - gocritic
#    #    - gocyclo
#    #    - gofmt
#    # - golint
#    - gocritic
#    # - goimports
#    - gosec
#    - stylecheck
#    - unconvert
#  disable:
#    - maligned
#    - unparam
#    - lll
#    - gochecknoinits
#    - gochecknoglobals
#    - dupl
#    - deadcode
#    - nakedret
#    - structcheck
#
#  enable:
#    - bodyclose
#    - deadcode
#    - dogsled
#    - dupl
#    - errcheck
#    - errname
#    - errorlint
#    - exhaustive
#    - exportloopref
#    - funlen
#    - gochecknoinits
#    - goconst
#    - gocritic
#    - gocyclo
#    - gofmt
#    - goimports
#    - gomnd
#    - goprintffuncname
#    - gosec
#    - gosimple
#    - govet
#    - ifshort
#    - ineffassign
#    # - lll
#    - makezero
#    - misspell
#    - nakedret
#    - noctx
#    - nolintlint
#    - revive
#    - staticcheck
#    - structcheck
#    - stylecheck
#    # - testpackage
#    - typecheck
#    - unconvert
#    - unparam
#    - unused
#    - varcheck
#    - whitespace

