// Code generated by "stringer -type=CopyMergeStrategy -linecomment"; DO NOT EDIT.

package cms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-0]
	_ = x[Ignore-1]
	_ = x[Must-2]
	_ = x[ClearIfEq-13]
	_ = x[KeepIfNotEq-14]
	_ = x[ClearIfInvalid-15]
	_ = x[ClearIfMissed-16]
	_ = x[NoOmit-22]
	_ = x[OmitIfEmpty-23]
	_ = x[OmitIfNil-24]
	_ = x[OmitIfZero-25]
	_ = x[NoOmitTarget-32]
	_ = x[OmitIfTargetEmpty-33]
	_ = x[OmitIfTargetNil-34]
	_ = x[OmitIfTargetZero-35]
	_ = x[SliceCopy-52]
	_ = x[SliceCopyAppend-53]
	_ = x[SliceMerge-54]
	_ = x[MapCopy-72]
	_ = x[MapMerge-73]
	_ = x[Flat-83]
	_ = x[UnexportedToo-93]
	_ = x[ByOrdinal-94]
	_ = x[ByName-95]
	_ = x[Shallow-96]
	_ = x[MaxStrategy-97]
	_ = x[ftf100-126]
	_ = x[ftf110-137]
	_ = x[ftf120-148]
	_ = x[ftf130-159]
	_ = x[ftf140-170]
	_ = x[ftf150-181]
	_ = x[ftf160-192]
	_ = x[ftf170-203]
	_ = x[InvalidStrategy - -1]
}

const _CopyMergeStrategy_name = "InvalidStrategystd-mustcleareqkeepneqclearinvalidclearmissednoomitomitemptyomitnilomitzeronoomittgtomitemptytgtomitniltgtomitzerotgtslicecopyslicecopyappendslicemergemapcopymapmergeflatprivatebyordinalbynameshallowMaxStrategyftf100ftf110ftf120ftf130ftf140ftf150ftf160ftf170"

var _CopyMergeStrategy_map = map[CopyMergeStrategy]string{
	-1:  _CopyMergeStrategy_name[0:15],
	0:   _CopyMergeStrategy_name[15:18],
	1:   _CopyMergeStrategy_name[18:19],
	2:   _CopyMergeStrategy_name[19:23],
	13:  _CopyMergeStrategy_name[23:30],
	14:  _CopyMergeStrategy_name[30:37],
	15:  _CopyMergeStrategy_name[37:49],
	16:  _CopyMergeStrategy_name[49:60],
	22:  _CopyMergeStrategy_name[60:66],
	23:  _CopyMergeStrategy_name[66:75],
	24:  _CopyMergeStrategy_name[75:82],
	25:  _CopyMergeStrategy_name[82:90],
	32:  _CopyMergeStrategy_name[90:99],
	33:  _CopyMergeStrategy_name[99:111],
	34:  _CopyMergeStrategy_name[111:121],
	35:  _CopyMergeStrategy_name[121:132],
	52:  _CopyMergeStrategy_name[132:141],
	53:  _CopyMergeStrategy_name[141:156],
	54:  _CopyMergeStrategy_name[156:166],
	72:  _CopyMergeStrategy_name[166:173],
	73:  _CopyMergeStrategy_name[173:181],
	83:  _CopyMergeStrategy_name[181:185],
	93:  _CopyMergeStrategy_name[185:192],
	94:  _CopyMergeStrategy_name[192:201],
	95:  _CopyMergeStrategy_name[201:207],
	96:  _CopyMergeStrategy_name[207:214],
	97:  _CopyMergeStrategy_name[214:225],
	126: _CopyMergeStrategy_name[225:231],
	137: _CopyMergeStrategy_name[231:237],
	148: _CopyMergeStrategy_name[237:243],
	159: _CopyMergeStrategy_name[243:249],
	170: _CopyMergeStrategy_name[249:255],
	181: _CopyMergeStrategy_name[255:261],
	192: _CopyMergeStrategy_name[261:267],
	203: _CopyMergeStrategy_name[267:273],
}

func (i CopyMergeStrategy) String() string {
	if str, ok := _CopyMergeStrategy_map[i]; ok {
		return str
	}
	return "CopyMergeStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
}
