// Code generated by "stringer -type=CopyMergeStrategy -linecomment"; DO NOT EDIT.

package cms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-0]
	_ = x[Ignore-1]
	_ = x[Must-2]
	_ = x[ClearIfEq-13]
	_ = x[KeepIfNotEq-14]
	_ = x[ClearIfInvalid-15]
	_ = x[ClearIfMissed-16]
	_ = x[NoOmit-22]
	_ = x[OmitIfEmpty-23]
	_ = x[OmitIfNil-24]
	_ = x[OmitIfZero-25]
	_ = x[NoOmitTarget-32]
	_ = x[OmitIfTargetEmpty-33]
	_ = x[OmitIfTargetNil-34]
	_ = x[OmitIfTargetZero-35]
	_ = x[SliceCopy-52]
	_ = x[SliceCopyAppend-53]
	_ = x[SliceMerge-54]
	_ = x[MapCopy-72]
	_ = x[MapMerge-73]
	_ = x[Flat-83]
	_ = x[UnexportedToo-93]
	_ = x[ByOrdinal-94]
	_ = x[ByName-95]
	_ = x[MaxStrategy-96]
	_ = x[ftf100-125]
	_ = x[ftf110-136]
	_ = x[ftf120-147]
	_ = x[ftf130-158]
	_ = x[ftf140-169]
	_ = x[ftf150-180]
	_ = x[ftf160-191]
	_ = x[ftf170-202]
	_ = x[InvalidStrategy-9223372036854775807]
}

const _CopyMergeStrategy_name = "std-mustcleareqkeepneqclearinvalidclearmissednoomitomitemptyomitnilomitzeronoomittgtomitemptytgtomitniltgtomitzerotgtslicecopyslicecopyappendslicemergemapcopymapmergeflatprivatebyordinalbynameMaxStrategyftf100ftf110ftf120ftf130ftf140ftf150ftf160ftf170InvalidStrategy"

var _CopyMergeStrategy_map = map[CopyMergeStrategy]string{
	0:                   _CopyMergeStrategy_name[0:3],
	1:                   _CopyMergeStrategy_name[3:4],
	2:                   _CopyMergeStrategy_name[4:8],
	13:                  _CopyMergeStrategy_name[8:15],
	14:                  _CopyMergeStrategy_name[15:22],
	15:                  _CopyMergeStrategy_name[22:34],
	16:                  _CopyMergeStrategy_name[34:45],
	22:                  _CopyMergeStrategy_name[45:51],
	23:                  _CopyMergeStrategy_name[51:60],
	24:                  _CopyMergeStrategy_name[60:67],
	25:                  _CopyMergeStrategy_name[67:75],
	32:                  _CopyMergeStrategy_name[75:84],
	33:                  _CopyMergeStrategy_name[84:96],
	34:                  _CopyMergeStrategy_name[96:106],
	35:                  _CopyMergeStrategy_name[106:117],
	52:                  _CopyMergeStrategy_name[117:126],
	53:                  _CopyMergeStrategy_name[126:141],
	54:                  _CopyMergeStrategy_name[141:151],
	72:                  _CopyMergeStrategy_name[151:158],
	73:                  _CopyMergeStrategy_name[158:166],
	83:                  _CopyMergeStrategy_name[166:170],
	93:                  _CopyMergeStrategy_name[170:177],
	94:                  _CopyMergeStrategy_name[177:186],
	95:                  _CopyMergeStrategy_name[186:192],
	96:                  _CopyMergeStrategy_name[192:203],
	125:                 _CopyMergeStrategy_name[203:209],
	136:                 _CopyMergeStrategy_name[209:215],
	147:                 _CopyMergeStrategy_name[215:221],
	158:                 _CopyMergeStrategy_name[221:227],
	169:                 _CopyMergeStrategy_name[227:233],
	180:                 _CopyMergeStrategy_name[233:239],
	191:                 _CopyMergeStrategy_name[239:245],
	202:                 _CopyMergeStrategy_name[245:251],
	9223372036854775807: _CopyMergeStrategy_name[251:266],
}

func (i CopyMergeStrategy) String() string {
	if str, ok := _CopyMergeStrategy_map[i]; ok {
		return str
	}
	return "CopyMergeStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
}
